### PR TITLE
Add missing WorkType filter

### PR DESCRIPTION
**Pull request by wodow**
Frontend part of https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/211

### CODE REVIEW

**Comment by wodow** [comment]
Pre-release: need to add strings for 

1. `$t('worksiteFilters.missing_information')` 
2. `$t('worksiteFilters.missing_work_type')`

**Comment by aarontitus** [comment]
For now, add this: $t('~~Missing Information') 
We automatically remove the double tildes, and this cues me to search and replace the string with a localization.

**Comment by wodow** [comment]
will do!

**Comment by wodow** [comment]
done

**Pull request merged**
