### PR TITLE
WIP fix(compat): Support IE11

### PR DESCRIPTION
**Pull request by BradenM**
Attempting to support IE11, may be a dark path :grimacing:

Currently managed to load the page w/o any errors and even get Vue to initialize, but it now stalls on a blank page without flashing any obvious errors.

See #702

### CODE REVIEW

**Comment by aarontitus** [comment]
Braden, that's great and all, but we don't want to spend ANY time supporting IE. We have many more very large issues to deal with.
If IE is really just a white screen,  then I guess that should solve most of the problems. :-)

**Comment by BradenM** [comment]
@aarontitus Ah, I misunderstood. Thought you *didnt* like the blank screen and at least wanted the users to see the page load and receive the banner. :+1:

**Comment by aarontitus** [comment]
Oh, my bad for not being clear. Sorry about that. While the banner would be nice to see, it's definitely not worth any time. Let's just leave it as-is for now.

**Comment by deepanchal** [comment]
Outdated

**Pull request closed without merging**
