### PR TITLE
Split User.states into global and per-incident

### PR DESCRIPTION
**Pull request by wodow**
Split `User.states` into global and per-incident; store and restore using both, backwards-compatibly.

Resolves https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/676

### CODE REVIEW

**Comment by wodow** [comment]
@tabiodun   I think this is fine but need a second opinion about whether could cause issues with what the phone system/service is doing with the states at https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/master/src/services/phone.service.js#L204

Should the `loggedInAgent` be (stored) global or per-incident in this new scheme?

**Comment by tabiodun** [comment]
@wodow Don’t worry about that. The phone service on that page isn’t in use

**Comment by wodow** [comment]
left this a while, but still works and solves the immediate problem, so merging.

**Comment by wodow** [comment]
Unnoticed and uncaught error from Vuex in this, so reverted.

**Pull request merged**
